### ISSUE TITLE
Dw20 1.12 - Versions

### ISSUE THREAD

**Issue by Keaton1188** [FTBTeam/FTB-Presents-Direwolf20-1.12#1]
Hi there... noticed a few issues with pack versions..

The FTB Launcher is showing Dw20 having a recommended version of 1.11.0 but the website (overview) is only showing 1.10.0 as recommended, and for the 1.11.0 files it has the 1.10.0 server files on it...

**Comment by SnowShock35** [comment]
Fixed.
