### ISSUE TITLE
OpenComputers PCs unusable

### ISSUE THREAD

**Issue by kevinkk525** [FTBTeam/FTB-Presents-Direwolf20-1.12#100]
* **Modpack Version**: 2.4

* **Issue**:  After installing OpenOS onto a HDD it initially works when rebooted and if the OpenOS Disk is installed but fails with "Unrecoverable Error computer halted" if rebooted, HDD removed and inserted, HDD inserted into a robot and similar. It makes using OC almost impossible as every reboot could lead to an unusable PC. 

This seems to be a bug that has been fixed: https://oc.cil.li/index.php?/topic/1808-computer-halted-error/

The PC save files are empty and the bug has been fixed in a new OC version

* **Is it Repeatable?**: Yes

* **Mod/s Affected**:  Opencomputers 1.7.2.67

* **Known Fix**: Update Mod, disable BufferChanges: opencomputers settings.conf the filesystem config "bufferChanges=true" to false (Confirmed working in SinglePlayer) if the mod won't be updated.

**Comment by SnowShock35** [comment]
Already fixed in 2.5.0.
