### ISSUE TITLE
MemoryTester, is this possible?

### ISSUE THREAD

**Issue by Shybella** [FTBTeam/FTB-Presents-Direwolf20-1.12#101]
Hello,

Thank you for taking the time to update the pack. 

Curse link: https://minecraft.curseforge.com/projects/memorytester

This will pop up a nice GUI before the game reaches the forge screen and will tell the client if they do not have enough memory assigned. You can post information there on how-to increase your memory settings in Twitch. 

Unsure of where to suggest things, sorry if this is the wrong place to do that. 
Thank you again.

**Comment by SpiritWolfie** [comment]
It was updated?

I don't see any updates

**Comment by SnowShock35** [comment]
@Shybella I don't have control on what mods are in the pack. The pack is now in its Long term support phase meaning it will likely have no additions or removed mods going forward. In addition, the pack already states it needs at least 4gb of ram to run in the description of the pack. I may tweak this when it comes time to update the pack again to suggest a higher ram usage.

@SpiritWolfie Yes the pack has been updated to 2.5.0 which is the current beta. It will appear on the Twitch Desktop App within a few minutes/hours/days. It depends entirely on their system. This isn't something we can control. For now, it is available via the FTB Launcher if you wish to try out the new version.

**Comment by SpiritWolfie** [comment]
@SnowShock35 

Can you please link?

I have checked Feed-the-beast.com under Files, I have checked twitch
Twitch states it was updated yesterday but doesn't show up under verisons, I have checked "Legacy" Client and I am not seeing the 2.5.0 anywhere

Sorry I'm getting off topic but I was hoping to update our server since the current 2.4.0 pack is beyond buggy for MP

**Comment by SnowShock35** [comment]
@SpiritWolfie Check issue #41. I left a comment there for you.
