### ISSUE TITLE
Twitch does not install/launch the 2.5.0 update correctly

### ISSUE THREAD

**Issue by Shybella** [FTBTeam/FTB-Presents-Direwolf20-1.12#103]
None of my players are able to use the 2.5.0 update as they get the error "Unable to set the reference of a object" or the pack loads without any mods. FTBLegacy launcher works fine, this is isolated to DW20 2.5.0 on the Twitch launcher.

**Comment by jenewland1999** [comment]
Hi Shybell,

Thanks for making me aware or this. I'll test for myself when I get home then I'll speak to the engineering team at Twitch. 

^Snow

**Comment by SnowShock35** [comment]
Hi @shybell

Thanks for the report. I'll take a look at this once I'm home and if need be report it to Twitch's Engineering Team. 

^Snow

**Comment by Shybella** [comment]
This is fixed now, thank you!
