### ISSUE TITLE
Launch Direwolf20 On less than 3GB of memory

### ISSUE THREAD

**Issue by Shybella** [FTBTeam/FTB-Presents-Direwolf20-1.12#104]
_(Tested by processing lots of chunk updates via random teleport)_
Proof:  https://i.imgur.com/UFWCKyq.gifv

_(Twitch Tutorial)_ 
Quick 15 sec gif: https://i.imgur.com/AJDeWgq.mp4

(Don't need a wall of flags, the less, the better)

JVM Arguments: `-XX:+UseG1GC -XX:MaxGCPauseMillis=5`

I saw you can speak to the Engineers at Twitch. The current collector that Twitch uses to launch the JVM  is deprecated and everything is moving to G1GC by default. 

Cons: It'll increase CPU usage slightly +2-5% on a i5 2500k (32nm processor).

**Comment by Sunekaer** [comment]
Hi

Not sure what the issue is here? 
Could you elaborate please?

**Comment by Shybella** [comment]
No issue was a suggestion for people less than 6GB of system memory and settings we found worked very well. 

Are you taking over snowshocks position?

**Comment by Sunekaer** [comment]
Thanks for the info.
I'm just assisting
