### ISSUE TITLE
/Dank/Null build 46 causes item loss "randomly"

### ISSUE THREAD

**Issue by Twisted-Code** [FTBTeam/FTB-Presents-Direwolf20-1.12#105]
* **Modpack Version**: 2.5.0

* **Issue**: Due to a [known issue with /Dank/Null](https://github.com/p455w0rd/DankNull/issues/156), build 46 of the mod can result in item loss upon opening one of the items added by the mod.
* **Link to Log or Crash File Paste**: I'm not certain you'll get anything useful from this, but [here you go](https://paste.feed-the-beast.com/view/1c0253e9) 

* **Is it Repeatable?**: Yes, it recurs on a seemingly random basis when opening a /dank/null
* **Mod/s Affected**: /Dank/Null v 1.12-1.4.46

* **Known Fix**: Use version 1.12-1.4.43 of the mod instead. I've tested this rather extensively with my private server and it doesn't seem to have the problem in question and, furthermore, this is corroborated by many of the participants in the issue I linked above

**Comment by SnowShock35** [comment]
Thanks for the report. 

When I get around to performing the next pack update I will be sure to look into this. Hopefully by then the author has addressed the issue if not I will most likely rollback the mod to an earlier version, providing it does not cause further issues.

**Comment by Twisted-Code** [comment]
I can't say for certain, but it seems to have been fixed completely at some point (in the mod that is; pack is still using the borked version .46 so Imma probably bump this issue soon). I haven't had any issues with the mod since updating it to build 80 on my private server, and it appears the issue on p455w0rd's tracker was closed on June 17. Good signs :-)

**Comment by 016Nojr** [comment]
I cant reproduce this with version 1.7.101, so hopefully we're all good
