### ISSUE TITLE
Block placement

### ISSUE THREAD

**Issue by smithd57** [FTBTeam/FTB-Presents-Direwolf20-1.12#106]
* **Modpack Version**: 1.12

* **Issue**: This is not really a bug more just a setting I am not sure how to disable in regards to block placement. The issue is I can place block directly on the location my character is currently standing which makes it difficult to build. Is there a way to turn this off?

**Comment by Icecreep109** [comment]
I am also having this problem.  Additionally, when placing blocks like ladders or levers, they attempt to place on south side of the block space - even if there is a valid side elsewhere.  Similarly, saplings can be placed anywhere, and even stacked on top of eachother (until a block update breaks them).

**Comment by SnowShock35** [comment]
Thanks for the issue. 

You are correct, this is an issue I came across when updating the pack I was not and still not sure of the cause of this issue so until a time I can find the source of the issue there is nothing I can do unfortunately.

**Comment by Tecotu** [comment]
Maybe Forge is causing this issue? They fixed a bug which maybe caused this problem in version 14.23.5.2822
