### ISSUE TITLE
Dual Monitor setup, fullscreen wont stick on 1 screen

### ISSUE THREAD

**Issue by BlowMonGool** [FTBTeam/FTB-Presents-Direwolf20-1.12#108]
* **Modpack Version**: FTB Direwolf 20 1.12.2 V2.50

* **Issue**:  When i Press f11 to set the game in full screen it streches out over the 2 monitors and that is exactly what i don't want, i want the full screen on 1 monitor, not 2

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by SnowShock35** [comment]
This is likely a miss-configured setting in your GPU's preferences. Depending on the model of your graphics card will depend on how you disable this and solve the issue.

**Comment by 016Nojr** [comment]
Works on my end, so unlikely an issue we're able to fix, if it still excists.
