### ISSUE TITLE
FTB direwolf20 1.12crashes when trying to open on singleplayer or on a server

### ISSUE THREAD

**Issue by Alexi248** [FTBTeam/FTB-Presents-Direwolf20-1.12#109]
Modpack Version: FTB Presents Direwolf20 1.12 Version: 2.5.0 Forge version: 14.23.5.2821

Issue: When trying to launch a single player game, i spawn in but i can never see where i spawned; all i see is my hot bar and with the books spawning into my inventory stuck in animation. After 5 seconds or so the game crashes. When i try this on a server, the first time i get in the server but never actually get into the game, i get kicked out with this message showing : " java.io.IOException: An established connection was aborted by the software in the host machine" and when i try to join again the game crashes.

Link to Log or Crash File Paste: https://paste.feed-the-beast.com/view/6c3a6f6d
Is it Repeatable?: yes.

Mod/s Affected: cannot even try the mods so not sure.

Known Fix: online fixes are outdated.

**Comment by MrJDubYou** [comment]
Any resolution on this? I'm having the same issue.

**Comment by Alexi248** [comment]
> Any resolution on this? I'm having the same issue.

yes I have solved the problem, I had turned a setting in the video settings off which was supposed to be on. I cannot check which one it is but if you could please show me a screenshot of the video settings i can tell you which one it is !

**Comment by MrJDubYou** [comment]
https://gyazo.com/23de8b617fe94f3abf8bf2def5586605

**Comment by Alexi248** [comment]
hmmmm what fixed it for me was turning VBOs on ... you already have it on and its not working... maybe try turning on Vsync ... if that fails then i don't have how else i can help you ... please let me know how it goes and good luck ! <3

**Comment by MrJDubYou** [comment]
No joy. I turned it off and on again with no luck.

**Comment by Alexi248** [comment]
owwww im sorry dude ... i tried what i can ... :(  
good luck though :/

**Comment by Sunekaer** [comment]
Please test with 2.6.0 which is available on the FTB App
