### ISSUE TITLE
Invisible hostile mobs 

### ISSUE THREAD

**Issue by Croompy** [FTBTeam/FTB-Presents-Direwolf20-1.12#111]
* **Modpack Version**: v2.5.0

* **Issue**: Invisible hostile mobs, can attack and move (do not appear on the journey map as well)

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/5aefed50

* **Is it Repeatable?**: I do not know how to re-create the bug, yet I've had this occurring multiple times now.

* **Mod/s Affected**: Journey map

* **Known Fix**: Non that i could find, only getting far enough away for them to despawn

**Comment by SuperSoaker420** [comment]
I'm also having this issue, happens with non-hostiles too (villagers).

**Comment by Sunekaer** [comment]
Please test with 2.6.0 which is available on the FTB App
