### ISSUE TITLE
Forge bug

### ISSUE THREAD

**Issue by Mrthomas20121** [FTBTeam/FTB-Presents-Direwolf20-1.12#112]
* **Modpack Version**: 2.5.0

* **Issue**: forge bug that allow you to place bug where you are standing. 

* **Is it Repeatable?**: happen every games

* **Mod/s Affected**: no mod affected

* **Known Fix**: update forge to a newer version. (don't know if the forge version after it fix it but the latest one work)

**Comment by Alpha-Knugen** [comment]
I have this bug aswell.
is it possible to download latest forge myself to fix it on the server and for me?
