### ISSUE TITLE
I can't seem to get LAN to work?

### ISSUE THREAD

**Issue by DragonFyreSoul** [FTBTeam/FTB-Presents-Direwolf20-1.12#113]
Hello, and I apologize if my request is unknowledgeable for I have little technological experience

FTB Direwolf 20 1.12 v2.4.0

The issue is that I cannot direct connect to a single-player world opened to LAN like in vanilla Minecraft. Whenever a server is joined a page pops up with a very long list of mismatched mods. Both my friend and I recently installed the modpack and attempted to play with each other only for us both to receive the mod mismatch page when trying to join each other. The game never fully crashed as a result, but I am still wondering what we might be doing wrong?

We tried multiple times to join each other to no avail, I will try to LAN with other people to see if it's only us

I can't seem to copy the page that pops up with the list of mods, I'll try to screenshot next time.

Thank you very much for hearing out this novice

**Comment by Sunekaer** [comment]
Hi 

If this still is an issue, please report the issue with attached log file from when the issue happened
