### ISSUE TITLE
Failed to connect to the server Disconnected

### ISSUE THREAD

**Issue by cerezabae** [FTBTeam/FTB-Presents-Direwolf20-1.12#114]
* **Modpack Version**: Direwolf 1.12 v2.5.0

* **Issue**: Every time I try to enter a server I get disconnected from it and cannot join. This started about a week ago. I was able to enter one server. Then, I wanted to join my friends' server and this error occurred. Now I am unable to join any server and get the same error - 

> "Failed to connect to the server 
> Disconnected"

The error looks exactly like this video - [https://www.youtube.com/watch?v=7YcQDMnkmA4](https://www.youtube.com/watch?v=7YcQDMnkmA4) I have read the comments too yet none of the suggestions have helped. It seems that I am entering the server but being disconnected right afterward.

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: Happens every time I enter a server

* **Known Fix**: n/a

**Comment by cerezabae** [comment]
Edit: I have added a log, sorry it's in an awkward format. I don't know how to fix it.
https://paste.feed-the-beast.com/view/da2288f3

One thing to note is that I am actually entering the server. 
=`16:26:36
net.minecraft.client.gui.GuiNewChat
Client thread
info
[CHAT] _Cereza joined the network`

**Comment by EMatzke1** [comment]
I'm having the same issue.

I've tried reinstalling the pack and fiddling with my router, but nothing works.

**Comment by Sunekaer** [comment]
Please test with 2.6.0 which is available on the FTB App
