### ISSUE TITLE
Chests and Beds transparent

### ISSUE THREAD

**Issue by lays24mc** [FTBTeam/FTB-Presents-Direwolf20-1.12#115]
Hi,

i have a little problem and i don't know if it an issue. My beds an Chest are transparent when I move a little further away. Is this a general problem or what could be the cause? I don't use tp or optifine.

https://1drv.ms/u/s!AmkINmSGuoq5jDxYeBJXhNf-amKL
https://1drv.ms/u/s!AmkINmSGuoq5jD3JH5RKAYD9HgmB

Direwolf20 1.12 Version: 2.5.0

**Comment by Sunekaer** [comment]
Please test with 2.6.0 which is available on the FTB App
