### ISSUE TITLE
Soul Network Leakage

### ISSUE THREAD

**Issue by MitruMesre** [FTBTeam/FTB-Presents-Direwolf20-1.12#116]
* **Modpack Version**: 2.5.0

* **Issue**: My soul network has a leak somewhere. I currently have 3 lp in my soul network, and if I right click with a blood orb, it goes up to 203, then after a while back down to 3. The only things I have relating to Blood Magic are:
A Hellfire Forge
A T2 Blood Altar
A T1 Incense Altar
Water, Lava, and Seer sigils
Weak and Apprentice Blood Orbs
A Sentient Sword
A Sacrificial Dagger
Petty and Lesser Tartaric Gems
Sanguine Scientiem and Inspectoris Scandalum
Some arcane ashes (15/20)
A Lava Crystal (in a chest, apparently the Steam Dynamo from Thermal Expansion doesn't accept it)
I don't think it's the Lava Crystal since I'm not getting nausea, but I can't think of what else would be draining my LP.

* **Link to Log or Crash File Paste**: It didn't crash the game so I dont have a crash file

* **Is it Repeatable?**: Yes, just add LP to any Blood Orb

**Comment by Sunekaer** [comment]
Hi MitruMesre,

Is this still an issue?
