### ISSUE TITLE
Unable to install v2.5.0 due to missing dependencies 306612

### ISSUE THREAD

**Issue by LemADEC** [FTBTeam/FTB-Presents-Direwolf20-1.12#117]
* **Modpack Version**: 2.5.0

* **Issue**: Fails to install due to missing dependencies

* **Link to Log or Crash File Paste**:
![image](https://user-images.githubusercontent.com/4776032/59877130-7860af80-93a5-11e9-9110-afe9510c53bc.png)

* **Is it Repeatable?**: yes, on 2 different computers from 2 different users in 2 different states

* **Mod/s Affected**: dependencies 306612

* **Known Fix**: none

**Comment by GrumpyChunks** [comment]
Temporary glitch maybe? v2.5.0 has just installed fine for me.

**Comment by LemADEC** [comment]
yes, looks like it

**Comment by Sunekaer** [comment]
Hi 
This is an issue with Twitch, sadly not something we can fix
