### ISSUE TITLE
Crash when trying to enter single player world

### ISSUE THREAD

**Issue by aidandelmoral** [FTBTeam/FTB-Presents-Direwolf20-1.12#118]
* **Modpack Version**:  Direwolf20 1.12 2.5 

* **Issue**:  When I try to enter my single player world I get this message "The game crashed whilst exception in server tick loop
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MineTogetherServer (minetogetherserver)" 

* **Link to Log or Crash File Paste**:  https://paste.feed-the-beast.com/view/fa0ccb9b 

* **Is it Repeatable?**:  this has happened multiple times 

* **Mod/s Affected**:  I have no idea but the error message says minetogherserver which I have no idea what that is 

* **Known Fix**:  if you know of a fix please let me know! Thanks

**Comment by niosxe07** [comment]
First when i load the mod pack it dosent show my worlds. After i update the modpack in twitch i could see my worlds, but when i load one off the worlds, it does crash.
And i have the same carsh

modpack: Sky Odyssey

**Comment by Sunekaer** [comment]
Hi,
please reupload log, as it's not available anymore
