### ISSUE TITLE
MineTogetherServer crash that never happened to me before.

### ISSUE THREAD

**Issue by ShadowSans55** [FTBTeam/FTB-Presents-Direwolf20-1.12#119]
* **Modpack Version**: 2.5.0

* **Issue**: I could play this pack totally fine until 10 minutes ago. I loaded the pack and now I can't load my singleplayer world anymore.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/a9b33383

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: MineTogether.

**Comment by Sunekaer** [comment]
Hi,
please reupload log, as it's not available anymore
