### ISSUE TITLE
Coal Dup glitch

### ISSUE THREAD

**Issue by catfinch** [FTBTeam/FTB-Presents-Direwolf20-1.12#12]
* **Modpack Version**: 2.0.0
* **Issue**: Coal can be duplicated infinitely by grinding to dust in the SAG mill and smelting back to coal in a redstone furnace. Because the SAG mill can give more than one piece of coal dust, it's possible to get more than 1 piece of coal back from grinding a single piece, for a small portion of the power requirement.

* **Link to Log or Crash File Paste**: n/a (not a crash)

* **Is it Repeatable?**: yes

* **Mod/s Affected**: EnderIO + Thermal Expansion

* **Known Fix**: disable the redstone furnace recipe for turning coal dust into coal, or increase it's power requirement

**Comment by Ozzymud** [comment]
Happens to Direwolf20 in his SevTech Ages let's play. I don't play on servers and have never seen it happen in SSP or LAN. But here is the episode, both Pahimar and him get stuck in the ground: https://youtu.be/KXYY4_rmjBI?t=752
