### ISSUE TITLE
DeepRes+IndustrialForegoing crash

### ISSUE THREAD

**Issue by AndyCAdams** [FTBTeam/FTB-Presents-Direwolf20-1.12#121]
* **Modpack Version**: Direwolf20 2.5.0

* **Issue**: https://cdn.discordapp.com/attachments/600548826297794577/603385828777132036/unknown.png

from the user that encountered the bug: "like literally all I did was shift click some bottles of water into that machine"

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/6a93127a

* **Is it Repeatable?**: everytime the user, or any user that logged out in the area, joins the server, the server crashes

* **Mod/s Affected**: do believe this is DeepResonance + Industrial Foregoing

* **Known Fix**: rolled back server to before offending moment

**Comment by Sunekaer** [comment]
please reupload log, as it's not available anymore
Which IF Block is that?
