### ISSUE TITLE
Quantum Quarry Interface Issue

### ISSUE THREAD

**Issue by Scultone** [FTBTeam/FTB-Presents-Direwolf20-1.12#122]
* **Modpack Version**: Direwolf20 1.12 v2.5.0           extrautils2-1.12-1.9.9

* **Issue**: Unable to access quantum quarry interface. Right click on any block and nothing happens. This pack was downloaded direct from twitch.  I have deleted the mod file on both server and client then readded before launching server and client.

* **Link to Log or Crash File Paste**: Not A Crash

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Extra Utilities 2

* **Known Fix**: I do not know a fix for this issue

any assistance would be appreciated.

**Comment by NathanH759** [comment]
Getting same issue ^

**Comment by Sunekaer** [comment]
Hi

From testing in my dev world it works fine, are you sure you build the multiblock correct?
Do you have a log file from where you clicked the block?
