### ISSUE TITLE
Aternos Server crash after using Openblocks Elevator (DW20 2.5.0, 1.12.2)

### ISSUE THREAD

**Issue by Nirvaxstiel** [FTBTeam/FTB-Presents-Direwolf20-1.12#124]
- Modpack Version: Direwolf20 1.12 v2.5.0
- Issue: Hosting DW20 on Aternos with a group of 4~6. Aternos server stops at some form of interaction with the elevator.
**Observations:**
- 1. Unable to purposefully re-create the problem by spamming shift and jump repeatedly.
- 2. The crash can happen any time between freshly started server and behaving normally for hours before a random crash occurs.
- 3. Counts of server crash have all been related to players interacting with the Elevator block (Going up or down)

- Link to Log or Crash File Paste: https://mclo.gs/UI6z9cQ#L3687 (Start from Line #3687)
- Is it Repeatable?: No, but all crashes have been reported to have happened when interacting with the Elevator block.

- Mod/s Affected: Openblocks(?)
- Known Fix: Unknown

**Comment by Sunekaer** [comment]
Hi Nirvaxstiel,

Could you please paste the log again? as the link isn't valid anymore
https://paste.feed-the-beast.com/
