### ISSUE TITLE
Resources Disappearing In Dank/Null

### ISSUE THREAD

**Issue by AllHopeLost** [FTBTeam/FTB-Presents-Direwolf20-1.12#125]
* **Modpack Version**: 2.5.0

* **Issue**: Upon Depositing any type of resources inside of any tier of Dank/Null exceding A stack proceeds to void said resource into oblivion and is nonexistent. Resources affected by bug is incorrigible.    

* **Link to Log or Crash File Paste**: No crash, Possible data available, Will update if found 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Mod [Dank/Null]
                                    Version: 1.4.46

* **Known Fix**: No known soft workarounds. Currently available solution is to rollback or update to newer version.

* **Additional Notes**: Bug is only present in1.4.46 and is repeatable in other mod packs using 
                                      said version
                                      [https://github.com/FTBTeam/FTB-Revelation-2/issues/290](url)

  using 1.4.43 Has no adverse affect to pack and have been tested personally 
                                      on my private server using current version of the pack 2.5.0

**Comment by Sunekaer** [comment]
Please test with 2.6.0 which is available on the FTB App

**Comment by AllHopeLost** [comment]
> Please test with 2.6.0 which is available on the FTB App

Do you mean the Twitch app , or is there another launcher/software I can download from ?.
The most recent version on the twitch launcher is 2.5.0

**Comment by Sunekaer** [comment]
The FTB App
Can be downloaded at feed-the-beast.com

**Comment by AllHopeLost** [comment]
> The FTB App
> Can be downloaded at feed-the-beast.com

Attemping to download the Server pack brings be to a white page with just this text

{"status":"error","message":"Authorization failed.","userKey":null}

**Comment by Sunekaer** [comment]
Okay the app is new, could you report it at https://github.com/FTBTeam/FTB-App/issues with version of the pack and OS

**Comment by AllHopeLost** [comment]
> Okay the app is new, could you report it at https://github.com/FTBTeam/FTB-App/issues with version of the pack and OS

Posted https://github.com/FTBTeam/FTB-App/issues/86

**Comment by Sunekaer** [comment]
Thanks a lot

**Comment by agrudsky** [comment]
I'm still having this problem as of pack version 2.6.0.

**Comment by Sunekaer** [comment]
#105
