### ISSUE TITLE
EnderIO Refined Storage Conduit does not pull from 1st slot of SAG Mill

### ISSUE THREAD

**Issue by vedrit** [FTBTeam/FTB-Presents-Direwolf20-1.12#126]
* **Modpack Version**: 2.5.0

* **Issue**: EnderIO Refined Storage Conduit does not pull items from the first slot of SAG Mill

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Refined Storage 1.6.12, EnderIO  5.0.40

* **Known Fix**: Workaround is to use an Item Conduit or similar block to pull from SAG Mill into a chest, then use an Importer

**Comment by Sunekaer** [comment]
Hi 

with Refined Storage Conduit you still need to use an importer
