### ISSUE TITLE
Pack update

### ISSUE THREAD

**Issue by Shybella** [FTBTeam/FTB-Presents-Direwolf20-1.12#128]
Hello,

The modpack is great and with over 1 million downloads it hasn't been updated since March. Basic mod update is needed! 

Thank you

**Comment by WolfBV** [comment]
Y e s

**Comment by Pantsema** [comment]
Definitly, I've encountered some issues in gameplay. As per today without any problem the following mods can be updated to the latest versions fixing issues in the pack:

/dank/null
Issues: fixing issues in the packs version with items voiding.
Link: https://www.curseforge.com/minecraft/mc-mods/dank-null/files/2831353
+Libs: https://www.curseforge.com/minecraft/mc-mods/p455w0rds-library/files/2830265

CompactMachines: 
Issue: Placing blocks inside a compactmachine directly connected to a Redstone tunnel
https://www.curseforge.com/minecraft/mc-mods/compact-machines/files/2707509

More?

**Comment by Sunekaer** [comment]
Working on it

**Comment by Sunekaer** [comment]
2.6.0 available on the FTB App
