### ISSUE TITLE
Repeated crash during End Dragon Fight (Vanilla Dragon)

### ISSUE THREAD

**Issue by FridgeBoy** [FTBTeam/FTB-Presents-Direwolf20-1.12#13]
* **Modpack Version**: 2.0.0

* **Issue**: Crash Upon loading into the game after the vanilla dragon landed in the center and used his breath attack

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/4e9bb136

* **Is it Repeatable?**: I can log onto the server and keep crashin over and over again, but i can't recreate it in single player

* **Mod/s Affected**: No clue, anything affecting the Dragon and his attacks? Draconic Evolution maybe?

* **Known Fix**:

**Comment by SnowShock35** [comment]
Thanks for the report. I am unsure as to why you are experiencing this issue. It seems very odd indeed. Was the pack in any way modified? 

Thanks for helping to better the packs stability. 👍

**Comment by FridgeBoy** [comment]
The pack was not modified in any way. Though to clear up a little confusion that might have occured, It's specifically the breath attack that leaves behind the circle of dragon breath which you can then right click with a bottle to get the "Dragon's Breath" item.

I was previously attacked by the sphere's the dragon shoots which also leave behind one of those "Dragon breath fields" which did not cause a crash.

**Comment by SnowShock35** [comment]
Thanks for getting back to me so quickly. So far there are a few possibilities as to what is causing that issue. However, it's not easy to really know where or what the specific cause is. This could be a bug with Minecraft, Forge or a mod doing something.

I wish I could be of more help right now with this issue but I think it's going to take some time to get to the bottom of this one. I will update this issue with any findings.

**Comment by FridgeBoy** [comment]
my friend lordmau5 got into contact with me about how "Mattabase retweeted a SnowShock tweet about an extremely weird crash, He then checked who posted it and i saw my name" so i was informed pretty quickly about your answer

**Comment by insectdude1258** [comment]
This is happening on a server i play on as well.  Me and a friend immediately crashed upon entering the end. later after a server restart (im guessing dim became unloaded), i was able to log in. i attempted to fight the dragon, but crashed immediately after his breath attack. every time i would log into the server, i would hear a roar then crash. i tried setting all graphics options to lowest including particles, and it made no difference.
https://pastebin.com/j5pu46vi
Entity Type: minecraft:area_effect_cloud (net.minecraft.entity.EntityAreaEffectCloud)

**Comment by SnowShock35** [comment]
Since this issue has been sat dormant for so long I'm gonna go ahead and assume that it has been fixed in a later mod version that was included in an update after 2.0.0.
