### ISSUE TITLE
What am i looking at randomly turning off, and cannout find a way to turn it back on.

### ISSUE THREAD

**Issue by vexx101** [FTBTeam/FTB-Presents-Direwolf20-1.12#130]
* **Modpack Version**: <1.12 v.2.5.0>

* **Issue**: <During my playthrough on a server, my waila setting i believe from just enough items, has suddenly turned off, and i have yet to find a way to turn it back on.>

* **Mod/s Affected**: <Just Enough Items (JEI)>

* **Known Fix**: <If you know of a fix please let me know! Thanks -->

**Comment by Pantsema** [comment]
> Is not WAILA. What you mean is "The One Probe"-Mod. With the book from this mod you can set the correct display options.

Source: https://forum.feed-the-beast.com/threads/cant-turn-on-waila.269960/
