### ISSUE TITLE
Internal exeption java.io.ioexeption an existing connection was focibly closed by a remote host

### ISSUE THREAD

**Issue by RogueXD** [FTBTeam/FTB-Presents-Direwolf20-1.12#131]
Direwolf20 1.12

When trying to join a server i get this message

Internal exception java.io.ioexception an existing connection was forcibly closed by a remote host

the modpack works fine its just connecting to servers i somehow cant do

it is repeatable

no known working fix i can find

**Comment by Pantsema** [comment]
In order to investigate this issue you'll need to upload the log files (error log).

**Comment by Sunekaer** [comment]
Hi RogueXD,

Please post latest log from the server and client.

**Comment by lorismus** [comment]
I do have the same problem. Server und client log f.
[latest.log](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.12/files/4478078/latest.log)
[latest.log](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.12/files/4478073/latest.log)

**Comment by lorismus** [comment]
Sry here we go
[2020-04-14-1.log](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.12/files/4478083/2020-04-14-1.log)

**Comment by RogueXD** [comment]
sorry i cant help anymore since the server i was trying to join has since closed and ive stopped having issues,

**Comment by Sunekaer** [comment]
Thanks, can you test with version 2.6.0? available on the FTB App, i added a mod there hopefully should fix it @lorismus 

No problem @RogueXD
