### ISSUE TITLE
Crashes when opening my singleplayer world

### ISSUE THREAD

**Issue by ozone3101** [FTBTeam/FTB-Presents-Direwolf20-1.12#132]
* **Modpack Version**: 2.4.0

* **Issue**: Minecraft crashes on opening my world

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/954128fb

* **Is it Repeatable?**: yes

The file was working one day and then it wasnt, but i have no idea why.

**Comment by Pantsema** [comment]
Have you tried to follow the instructions as mentioned in the log?
> EnderStorage was unable to read it's data, please delete the 'EnderStorage' folder Here: C:\Users\cayde\OneDrive\Documents\Curse\Minecraft\Instances\FTB Presents Direwolf20 1.12\saves\New World\EnderStorage and start the server again.

Definitly something went wrong with EnderStorage, since mods are over time outdated in the modpack updating these specific mod could perhaps also resolve your issue.

**Comment by ozone3101** [comment]
Yeah that was the fix, I saw it in the crash log a few hours after I posted this but forgot to remove the post. 
Thanks for the help nonetheless.
