### ISSUE TITLE
Game crashes when looking up uses for the Enhanced Combustion Generator in JEI

### ISSUE THREAD

**Issue by xyzabc198** [FTBTeam/FTB-Presents-Direwolf20-1.12#14]
Modpack Version: 2.0

Issue: Game crashes whenever pressing "u" (In JEI to see what uses it has) on an Enhanced Combustion generator.

Link to Log or Crash File Paste: The game crashed whilst rendering item
Error: java.lang.ClassCastException: it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap cannot be cast to gnu.trove.map.hash.TIntObjectHashMap

Is it Repeatable?: Yes, just press "u" on the Enhanced Combusion Generator in JEI

Mod/s Affected: EnderIO/JEI

Known Fix: Unknown

**Comment by SnowShock35** [comment]
Thanks for the report. It appears as if this issue has been solved in the latest update of the pack 2.1.0. When the update is available, please take the time to see if your issue is resolved and let me know here. 

Thanks for helping to better the packs stability. 👍
