### ISSUE TITLE
Morph mod issue?

### ISSUE THREAD

**Issue by XxRosiexX** [FTBTeam/FTB-Presents-Direwolf20-1.12#141]
* **Modpack Version**: 2.7.0

* **Issue**: When using some of the morphs a white cube forms, is quite far away from the player itself but moves around witht he player. Then when transforming back to default form the player skin well breaks. Tested with & without optifine. Bug works both times.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes, All of my staff members and some players have repeated it.

* **Mod/s Affected**: Morph Mod

* **Known Fix**:

**Comment by 016Nojr** [comment]
Morph mod has been updated to the latest version in Pack version 2.8.0. If it wasnt fixed there it wont be fixed as the mod isnt being maintained for 1.12 anymore.
