### ISSUE TITLE
Duplicating speed upgrades

### ISSUE THREAD

**Issue by djacicd** [FTBTeam/FTB-Presents-Direwolf20-1.12#145]
* **Modpack Version**: 1.2

* **Issue**: Speed upgrade duplication (it also destroys first crafting pattern if there's any)

* **Link to Log or Crash File Paste**: ///

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Extrastorage

* **Known Fix**: ///

* **Youtube Video**: https://www.youtube.com/watch?v=h5fLtL2axkM

**Comment by 016Nojr** [comment]
https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16 is the repo for the pack, this is the 1.12 version.
