### ISSUE TITLE
rats + mekanism = BAD.

### ISSUE THREAD

**Issue by wormodyssey** [FTBTeam/FTB-Presents-Direwolf20-1.12#146]
ok so the rats auto curdler when you put a mekanism basic liquid tank in it full of milk, crashes the game and uh you have to disable RATS and delete all of you hard-earned, and bread, rats.

**Comment by 016Nojr** [comment]
https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16 is the repo for the pack, this is the 1.12 version.
