### ISSUE TITLE
Ender IO Experience Obelisk isn't accepting exp manually.

### ISSUE THREAD

**Issue by Sacredspawn** [FTBTeam/FTB-Presents-Direwolf20-1.12#150]
* **Modpack Version**:  2.9.0

* **Issue**: When using the ender IO Experience obelisk, it is possible for it to pull from nearby inventories, but the greatest function of it, the ability to manually insert experience isn't functioning. anything other than manual experience insertion works just fine. 

* **Link to Log or Crash File Paste**: I don't have a crash file as the game didn't crash 

* **Is it Repeatable?**:  It's not exactly the kind of issue that stops. Every attempt to put experience into an experience obelisk manually has failed. 

* **Mod/s Affected**: Just Ender IO 

* **Known Fix**:  nope

**Comment by CitiesXL2815** [comment]
it's been Fixed in Dev on EnderIO https://github.com/SleepyTrousers/EnderIO/issues/5487

**Comment by 016Nojr** [comment]
When the next pack update is released it will be fixed if the mod has been updated by then
