### ISSUE TITLE
Prismarine Dupe Recipes 

### ISSUE THREAD

**Issue by Kanzuke117** [FTBTeam/FTB-Presents-Direwolf20-1.12#17]
* **Modpack Version**: 2.0.0

* **Issue**: It is possible to dupe Prismarine through use of the Thermal Expansion Factorizer, which can turn Prismarine Bricks into 9 Shards, which can be turned into 2 Prismarine with the vanilla recipe, which can be turned into 2 Prismarine Bricks using a Chisel

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Thermal Expansion, Chisel

* **Known Fix**: I think the most sensible solution would be to disable the Factorizer recipe, making Prismarine only available through mob-drops or atomic reconstruction. This would more accurately represent how rare most mods treat it as for end-game recipes.

**Comment by SnowShock35** [comment]
Thanks for reporting this issue. I can confirm that this indeed does cause a duplication bug. As it currently stands I'm not certain Factorizer recipes can be altered. Also, even if they could, being able to chisel between the three Prismarine varients shouldn't be allowed as their recipes cost different amounts of ingredients, therefore, they're not equal and therefore they shouldn't be chisel-able between the three variants. 

As such, I've disabled chiselling of the vanilla Prismarine variants until such time that Factorizer recipe support is available or I decide that the recipe should be re-enabled.

Thanks for helping to better the packs stability. 👍
