### ISSUE TITLE
Tiny Dry Rubber to Dry Rubber

### ISSUE THREAD

**Issue by Redeye123** [FTBTeam/FTB-Presents-Direwolf20-1.12#19]
* **Modpack Version**: 2.0.0

* **Issue**: Tiny Dry Rubber to Dry Rubber Does not work as the recipe in JEI says 

* **Link to Log or Crash File Paste**: 
![untitled](https://user-images.githubusercontent.com/828563/42636769-d8dc6a2c-85e9-11e8-9610-84bccbdee6c4.png)

* **Is it Repeatable?**: Yes try to make Dry Rubber 

* **Mod/s Affected**: Industial Foregoing

* **Known Fix**: Sadly No

**Comment by geratheon** [comment]
Pretty sure this recipe works. Did you tried to restart your client (and your server)?

**Comment by Redeye123** [comment]
F me did a restart and it works just fine ...
