### ISSUE TITLE
Thaumcraft taint seed spawners. Intentional? 

### ISSUE THREAD

**Issue by gcheezydog** [FTBTeam/FTB-Presents-Direwolf20-1.12#20]
* **Modpack Version**: 2.0.0
* **Issue**: Thaumcraft taint seeds are able to be duplicate in a enderio powered spawner. 

* **Mod/s Affected**: Thaumcraft and EnderIO

**Comment by SnowShock35** [comment]
I will have to get back to you on this one. I'm uncertain whether or not this is a bug as I've yet to play Thaumcraft in 1.12

**Comment by SnowShock35** [comment]
Fixed in [2.3.0](https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-12/files/2615409)
