### ISSUE TITLE
Game Crash When using Thaumic inventory scanner

### ISSUE THREAD

**Issue by HelpImDying** [FTBTeam/FTB-Presents-Direwolf20-1.12#21]
FTB-Presents-Direwolf20-1.12-2.0.0

The game Crashes when using the Thaumometer to inventory scan after canning s few item and trying to put the Thaumometer back into an inventory slot it tries to scan the slot as air and the game crashes.

[crash-2018-07-12_01.35.21-client.txt](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.12/files/2190254/crash-2018-07-12_01.35.21-client.txt)

yes

Thaumic inventory scanner

No fix found

**Comment by SnowShock35** [comment]
There's a reason the mod isn't the pack. 😉

**Comment by HelpImDying** [comment]
Hey snowShaock35 might what to take a second look there cause thaumic inventory scanning is i the 2.0.0 mad pack

**Comment by SnowShock35** [comment]
![](https://ss.snowshock35.com/2018/07/1531499722-86b65d3d.png) This is a picture of my dev instance as you can clearly see it's not there

**Comment by HelpImDying** [comment]
thats really odd cause i havent moddified the pack at all and have it

**Comment by HelpImDying** [comment]
so sure enough on a new install its done not sure what happened to make it get in there but problem solved i guess
