### ISSUE TITLE
Astral aquamarine

### ISSUE THREAD

**Issue by Drak0necal** [FTBTeam/FTB-Presents-Direwolf20-1.12#3]
Modpack Version --> 2.0.0

Issue--> no aquamarine spawning

known fix -->I am not a modpack creator but I thunk it is the same problem as seventech ages were dog pelt is not spawning but here it is not being generated.

**Comment by Kanzuke117** [comment]
Changelogs show
> - Astral Sorcery
>   - Disabled aquamarine generation
```diff
     # Defines how many aquamarine ores it'll attempt to generate in per chunk. 0 = disabled [range: 0 ~ 2048, default: 64]
-    I:generateAquamarineAmount=64
+    I:generateAquamarineAmount=0
```

It looks deliberate, but now the only way to get Aquamarine is void mining

**Comment by Drak0necal** [comment]
This is so into the modpack ,if I am supposed to get into void mining which
I consider being mid their mod that need a decent amount a power to get a
good supply of them, so I found a way to get a good bit to start since you
need them the most early-game which is just search in the lootr chests of
the shrines.

And something else that does not have to do with the aquamarines , Is the
modpack is missing some important kitchensink tweaks like disabling morph
abilities , I know that u want the modpack to be easy but you are supposed
to learn the mods and by you having access to flying early game by killing
a bat will make the player ignore the flying abilities in the modpack ....
And something else ,it is missing some Automation mods like mekanesim

Thanks for your time,
Khalid

**Comment by SnowShock35** [comment]
@Kanzuke117 @Drak0necal 

Aquamarine is supposed to generate it is not intended that it is off. The reason it's disabled in the Astral Sorcery config is that it's supposed to be done through CoFH World. For some reason, it doesn't appear to be working. I will take a look as soon as I can. 

Apologies for this inconvenience

**Comment by shellshock2020** [comment]
I’m also having an issue where my wand is not showing rock crystals. The white particles that are supposed to be comming up through the ground, no luck.
