### ISSUE TITLE
Thermal Dynamics with Optifine bug!

### ISSUE THREAD

**Issue by Critteros** [FTBTeam/FTB-Presents-Direwolf20-1.12#31]
I'm using newest version of direwolf20 modpack and I manually added Optifine mod to it. That caused 
 condiuits from TD not to render properly. Any alternatives to optifine?
![2018-07-22_00 52 03](https://user-images.githubusercontent.com/41534816/43043497-61b16f7a-8d95-11e8-9c18-451a2df09231.png)

**Comment by SnowShock35** [comment]
Optifine **is not** supported.
