### ISSUE TITLE
JEI not showing up

### ISSUE THREAD

**Issue by bradleysjc** [FTBTeam/FTB-Presents-Direwolf20-1.12#34]
JEI toolbar and tooltips are no longer showing up. ive tried pressing O and going into the settings to change the controls but this did not work

**Comment by SnowShock35** [comment]
The hotkey for making JEI show up isn't `O` it's `Ctrl+O`. Try this and if that doesn't work, try a fresh install of the pack. It's possible the update failed to complete 100%.

Let me know how you get on.
