### ISSUE TITLE
Bug with inventory sorting and Forestry Mining Backpack.

### ISSUE THREAD

**Issue by BrickVoid** [FTBTeam/FTB-Presents-Direwolf20-1.12#38]
* **Modpack Version**: 2.2.0

* **Issue**: Scroll wheel clicking in a Forestry Mining backpack to sort it deletes all items except one item and does not give them back.  It additionally does not sort the items as intended for this function.  When this happened, all items vanished and were replaced with a stack containing 25 Actually Additions Black Quartz.  Items from EnderIO, Immersive Engineering, and vanilla Minecraft were in the pack including Actually Additions ores, among other items, but they all vanished and got replaced with the above mentioned item.

* **Link to Log or Crash File Paste**: Unfortunately the log information did not appear to contain anything useful regarding the disappearance of the items therefore I cfannot submit one as it contains no useful information.

* **Is it Repeatable?**: This has happened in a previous version of the pack, it might be a cross-mod interaction with whatever mod adds the sorting for the chests.  It is an extremely annoying interaction and deletes items without warning, no possibility to get the items back.

* **Mod/s Affected**: Unsure which mods to put here please test and add as determined by testing.

* **Known Fix**: None that I know of.

**Comment by SnowShock35** [comment]
Fixed in [2.3.0](https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-12/files/2615409)
