### ISSUE TITLE
Portal gun from MeeCreeps - End Dimension

### ISSUE THREAD

**Issue by TwoPointInfinity** [FTBTeam/FTB-Presents-Direwolf20-1.12#48]
* **Modpack Version**: 2.2.0 and 2.1.0

* **Issue**: Using the meecreeps portal gun to leave the  End dimension messes up the inventory automatic refreshing. It seems you have to do something to refresh your inventory yourself like move something or open the trash can or another inventory to actually show something move. 

* **Is it Repeatable?**: Yes. Use the portal gun to travel from The End to the Overworld then try using a crafting grid from refined storage or applied energistics. Or just organize your inventory by middle clicking. Nothing works right its all kinda weird,

* **Mod/s Affected**: MeeCreeps

* **Known Fix**: Logging out of the server and logging back in fixes this issue. I have not tried this in single player.

**Comment by SnowShock35** [comment]
Hello @TwoPointInfinity 

Thank you for your contribution to the FTB Presents Direwolf20 1.12 mod-pack. Your involvement greatly helps to improve the quality of the product and keep it bug-free and more enjoyable for everyone. Without your input, the pack would cease to be as good as it is. 

This issue will shortly be reported to McJty (if it hasn't already). I will update this issue when there is some noteworthy news regarding it. 

Many thanks once again for your engagement here on the FTBTeam's GitHub.

**SnowShock35 ☃️**

***

> ![SnowShock35](https://cdn.snowshock35.com/avatar-rounded.png)
> ### SnowShock35
> @FTBTeam Pack Developer, Aspiring Full-Stack Engineer, 
> UoN Student, Mod & Modpack Developer, Casual Gamer,
> Nerd, Tea Drinker, Made in the UK 🏳️‍🌈

**Comment by SnowShock35** [comment]
Hi @TwoPointInfinity,

I have confirmed that this issue has been fixed in the upcoming 2.5.0 version of the mod pack. Please stay tuned for a beta release later this week.

Many thanks for your patients.
SnowShock35.
