### ISSUE TITLE
Applied Energistics 2 Mod Disabled

### ISSUE THREAD

**Issue by WoodwardWolf** [FTBTeam/FTB-Presents-Direwolf20-1.12#49]
* **Modpack Version**: 2.2.0

* **Issue**: I used to watch Direwolf all the time two or so years ago, so like old times I installed the mod package, turned his series on YouTube on the TV and started playing Minecraft the way it should be played. Unfortunately, I only made it to episode two when Dire built the 'Quartz Grindstone' from the mod 'Applied Energistics 2'. Here is where I had the issue, the recipe calls for a 'Wooden Gear' from 'Ender IO'. The item, its recipe and everything else seems to show up in the mod 'Just Enough Items' but when you go to the bench to create it, nothing 'visually' shows up in the output box yet it still consumes the 4 sticks it takes to make it (PS: I want my sticks back!) and acts as a placeholder item. I realized that when you put your mouse over the empty space that is suppose to be the gear, the game reads where its name should be "This Item Is Disabled." and underneath says "_Applied Energistics 2_". That's just about it, I'm guessing somewhere you disabled it while fixing something else is my guess. I'd love to be able to play still, hope you can get it!

* **Link to Log or Crash File Paste**: My game didn't crash, just isn't working right.

* **Is it Repeatable?**: To make sure it wasn't just my new PC, I installed Minecraft, Twitch and the package all from scratch on my surface pro laptop and the same issue repeated itself.

* **Mod/s Affected**: Applied Energistics 2 is the only mod that I am aware of but to be honest, I didn't get far into the game, this was within a half hour of gameplay, not even gotten to the point I was using other mods yet.

* **Known Fix**: I have no idea how to fix it, I even tried playing with the files and .jar names looking for a .disabled but this isn't exactly my realm of expertise sorry.

**Comment by SnowShock35** [comment]
@WoodwardWolf Do any of the AE2 items show up? E.g. the ore or any of the ae2 blocks in JEI?

**Comment by EmberQuill** [comment]
It looks like it's specifically the EnderIO Wooden Gear that has issues. I've run into the same problem myself. The Wooden Gear has four different recipes according to JEI, but only one of them crafts a wooden gear. Two of them craft other things and one of them crafts an invisible disabled item from AE2.

![Image](https://i.imgur.com/9pBOZCt.png)
![Image](https://i.imgur.com/B1ZvO5d.png)
![Image](https://i.imgur.com/sZVn8wk.png)
![Image](https://i.imgur.com/TbhPXgu.png)
![Image](https://i.imgur.com/bfGIwDs.png)

**Comment by SnowShock35** [comment]
Okay, I see what's going on here. 

So yes the AE2 gear is disabled. This is because of a feature in AE2 called ore camouflaging where if another mod adds a wooden gear it's one gets disabled but it appears that it's not working correctly as the recipe for some odd reason is still appearing. 

You have also pointed out to me from those screenshots that there are a few recipe conflicts with EIO wooden gear which I will additionally have to fix. 

However, for the time being, the final recipe you show should allow you to craft the grindstone. 

I will ensure this is addressed in the upcoming version of the pack. Thank you for your patients.

**Comment by WoodwardWolf** [comment]
That's fantastic, just glad you know what the issue is. I'll use that last recipe and move on, for now, thank you!

Appreciate all that you guys do

**Comment by SnowShock35** [comment]
Hello @WoodwardWolf 

Thank you for your contribution to the FTB Presents Direwolf20 1.12 mod-pack. Your involvement greatly helps to improve the quality of the product and keep it bug-free and more enjoyable for everyone. Without your input, the pack would cease to be as good as it is. 

I am delighted to inform you that this issue has been addressed in the recent development of the mod-pack and will be fixed as of version `version`, which will be released publically in the near future. 

As such this issue will now be marked for closure until the update is released and will be closed shortly following its release.

P.S. Sorry this small thing took so long. IRL got busy 🙂.

Many thanks once again for your engagement here on the FTBTeam's GitHub.

**SnowShock35 ☃️**

***

> ![SnowShock35](https://cdn.snowshock35.com/avatar-rounded.png)
> ### SnowShock35
> @FTBTeam Pack Developer, Aspiring Full-Stack Engineer, 
> UoN Student, Mod & Modpack Developer, Casual Gamer,
> Nerd, Tea Drinker, Made in the UK 🏳️‍🌈

**Comment by SnowShock35** [comment]
Fixed in [2.3.0](https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-12/files/2615409)
