### ISSUE TITLE
Portal issue

### ISSUE THREAD

**Issue by deamontemps** [FTBTeam/FTB-Presents-Direwolf20-1.12#5]
Version: 2.0.0
Issue:I am running a server with a few players on. We are having an issue where sometimes the portals (mining world and nether) will randomly teleport the user to a random spot in blocks. This has happened alot.

I have an unmodified version of the modpack. Running a brand new world from the start of the update.

**Comment by SnowShock35** [comment]
Hi there, 

Are you able to consistently repeat this bug? 
Does it occur in singleplayer or multiplayer or both?
How do you go about reproducing this issue?

If you could let me know answers to these questions that would be most helpful and with them I can hopefully help solve the problem you're having today.

**Comment by Ozzymud** [comment]
Happens to Direwolf20 in his SevTech Ages let's play. I don't play on servers and have never seen it happen in SSP or LAN. But here is the episode, both Pahimar and him get stuck in the ground: https://youtu.be/KXYY4_rmjBI?t=752

**Comment by SnowShock35** [comment]
@Ozzymud I am aware that it happens to Direwolf20 and Pahimar in that series, but that is a hunting dimension portal and a completely different pack all together. Are you experiencing this yourself? If so, what steps do you take for this issue to occur?

**Comment by deamontemps** [comment]
Sorry I have only just seen your reply;

I can repeat the bug in a way. It happens to other players rather then more. And it can be hit or miss (not a controllable bug.

The bug so far Has only been seen online. ( I am using clanforge as a server host)

To reproduce the bug just go through the portal but as i have said its 50% chance of it happening.

I do have a few theories and we noticed once or twice with the nether as well.

The main theory being portals being to close and the server doesn't quite know where to send the player. The pack is standerd

**Comment by SnowShock35** [comment]
Doesn't look like there's any resolution to this issue. At least that I can find. My advice is to keep on top of the pack updates and see if it fixes itself in time. There will be a new update soon which should fix a lot of issues so fingers crossed that should help. Unfortunately, that is all I can suggest at this time.
