### ISSUE TITLE
World randomly freezes

### ISSUE THREAD

**Issue by Mc-man165** [FTBTeam/FTB-Presents-Direwolf20-1.12#50]
* **Modpack Version**: 2.2.0

* **Issue**: Randomly my world just freezes and i cant open anything or interact with anything, i can still move around the world though. When looking at blocks the "waila" says waiting for server. I have left it for 10-15 min and nothing changes
 
* **Link to Log or Crash File Paste**: [https://paste.feed-the-beast.com/view/c82ad24a](url)

* **Is it Repeatable?**: It happens after a opening and closing inventories but its different ones every time and random in when it decides to "crash"

* **Mod/s Affected**: none

* **Known Fix**: saving and quiting and then using task manager to stop the prosses

**Comment by SnowShock35** [comment]
Hello @Mc-man165 

Thank you for your contribution to the FTB Presents Direwolf20 1.12 mod-pack. Your involvement greatly helps to improve the quality of the product and keep it bug-free and more enjoyable for everyone. Without your input, the pack would cease to be as good as it is. 

To my knowledge, this issue should be resolved in the upcoming version of the mod pack. I'd like to apologise for the lack of any response in so long there's been a lot going on in real life that hasn't given me much time to look at issues. 

If you continue to have problems after the release of 2.3.0 then it's probably safe to say that this is the result of world corruption. You will most likely have to load a backup. 

Many thanks once again for your engagement here on the FTBTeam's GitHub.

**SnowShock35 ☃️**

***

> ![SnowShock35](https://cdn.snowshock35.com/avatar-rounded.png)
> ### SnowShock35
> @FTBTeam Pack Developer, Aspiring Full-Stack Engineer, 
> UoN Student, Mod & Modpack Developer, Casual Gamer,
> Nerd, Tea Drinker, Made in the UK 🏳️‍🌈

**Comment by SnowShock35** [comment]
This issue has now been closed due to a dormant state.
