### ISSUE TITLE
minetogether issue server not being list in public list

### ISSUE THREAD

**Issue by Buzz1971** [FTBTeam/FTB-Presents-Direwolf20-1.12#51]
I have had my server on the public list, it was working fine I was getting new players on a daily basis and all of a sudden it stopped not sure what I did, I have tried to reset the server.properties like I did when I was able to list my server in the public list.
I have even updated the mod minetogether and went to latest release still nothing but I am getting this message currently in my console: "Curse project ID in creeperhost.cfg not set correctly - please set this to utilize the server list feature"
I don't have a project ID what do I do with it.
I also noticed a few days ago there was some error message about minetogether could not list correctly I never got a copy of the error so so I dont know what exactly it said.
can someone help I am searching all over for the answers but with no luck so far.

**Comment by SnowShock35** [comment]
Please follow the issue template provided.
