### ISSUE TITLE
Looking at enderIO recipes causes crash?

### ISSUE THREAD

**Issue by Zidane3838** [FTBTeam/FTB-Presents-Direwolf20-1.12#54]
* **Modpack Version**: 1.12-1.12.2-2.2.0

* **Issue**: checking recipes for quite clear glass and capacitor bank locks up minecraft and completely crashes.

* **Link to Log or Crash File Paste**: crash 1: https://paste.feed-the-beast.com/view/5eabf8da
crash 2: https://paste.feed-the-beast.com/view/a6d522fb
I got this each time too: https://paste.feed-the-beast.com/view/9a1e6826

* **Is it Repeatable?**: YES

* **Mod/s Affected**: only had it happen while looking at enderio recipes...

**Comment by RayYung** [comment]
It did the same to me a while ago but I didn't give much thought about it. It was 2.0.0 or 2.1.0 but I thought I would mention it.

**Comment by Zidane3838** [comment]
happened just now with the SAG Mill. Had my buddy also try it out and it also crashed his game.

**Comment by SnowShock35** [comment]
This issue has been closed due to being dormant for a long period of time.
