### ISSUE TITLE
State engine was in incorrect state World wont Load

### ISSUE THREAD

**Issue by Ugame45** [FTBTeam/FTB-Presents-Direwolf20-1.12#55]
As the title said world wont load tried looking around but couldnt find a solution

Modpack version-2.2.0

Issue-Everytime i try and load in my singleplayer world it will not load up and basically be stuck in the loading screen with no words or anything

Link to Log or Crash File Paste: https://pastebin.com/iaUAVMri

Is it Repeatable?: yes i've tried several times i even reinstalled the pack

Mod/s Affected: I have optifine but i tried without it still same results

**Comment by SnowShock35** [comment]
Hello,

Thank you for your contribution to the FTB Presents Direwolf20 1.12 mod-pack. Your involvement greatly helps to improve the quality of the product and keep it bug-free and more enjoyable for everyone. Without your input, the pack would cease to be as good as it is. 

I'm unsure what it is that is causing your issue. Are you still getting it on version 2.3.0 of the mod-pack? If so could you send me the log file located in `../logs/`. Hopefully that should give me more of an idea as to what is causing your issue. 

Failing that my advise to you would be to load an earlier backup from `../backups/` to see if one of those will allow you to play your world again. 

Let me know how you get on.

Many thanks once again for your engagement here on the FTBTeam's GitHub.

**SnowShock35 ☃️**

***

> ![SnowShock35](https://cdn.snowshock35.com/avatar-rounded.png)
> ### SnowShock35
> @FTBTeam Pack Developer, Aspiring Full-Stack Engineer, 
> UoN Student, Mod & Modpack Developer, Casual Gamer,
> Nerd, Tea Drinker, Made in the UK 🏳️‍🌈

**Comment by Ugame45** [comment]
Hey,

I have not checked in a bit since i first tried(a lot of times as the
report said) so its the log is about a week or so old
either way thanks for the help!

**Comment by SnowShock35** [comment]
Not to worry, happy to help. Happy Minecrafting!
