### ISSUE TITLE
Thaumcraft Plate Recipes

### ISSUE THREAD

**Issue by VT-14** [FTBTeam/FTB-Presents-Direwolf20-1.12#56]
* **Modpack Version**: All versions I have seen that include Thaumcraft 6 (2.0.0-2.2.0)
Included in the log is a custom modified versions 2.2.0.

* **Issue**: Thaumcraft's default plate crafting recipe (3 Ingots in a line = 3 Plates) was removed.  By default, they are only craftable using the Thermal Expansion Compressor or Immersive Engineering (Brass Plates can also be crafted using the Tinkers' Construct Smeltery).  Those machines may be undesirable as those are both Tech mods and Thaumcraft is a Magic mod.  It is also inconsistent with the other plate recipes, which work with hammers.

* **Link to Log or Crash File Paste**: 
FML: https://paste.feed-the-beast.com/view/b78239d2
No Crash

* **Is it Repeatable?**: Yes.  It has happened on all versions I've tried since Thaumcraft was added in 2.0.0.  I've even seen it in Direwolf's videos.

* **Mod/s Affected**: Thaumcraft

* **Known Fix**:
I added my own CraftTweaker scripts in the same style as the Thermal Foundation ones.  This adds recipes for the Immersive Engineering Hammer, IC2 Hammer, and 3 ingots = 1 plate.
https://paste.feed-the-beast.com/view/7fcfa4fe

**Comment by SnowShock35** [comment]
Hello @VT-14 

Thank you for your contribution to the FTB Presents Direwolf20 1.12 mod-pack. Your involvement greatly helps to improve the quality of the product and keep it bug-free and more enjoyable for everyone. Without your input, the pack would cease to be as good as it is. 

I am delighted to inform you that this issue has been addressed in the recent development of the mod-pack and will be fixed as of version 2.3.0, which will be released publically in the near future. 

As such this issue will now be marked for closure until the update is released and will be closed shortly following its release.

Many thanks once again for your engagement here on the FTBTeam's GitHub.

**SnowShock35 ☃️**

***

> ![SnowShock35](https://cdn.snowshock35.com/avatar-rounded.png)
> ### SnowShock35
> @FTBTeam Pack Developer, Aspiring Full-Stack Engineer, 
> UoN Student, Mod & Modpack Developer, Casual Gamer,
> Nerd, Tea Drinker, Made in the UK 🏳️‍🌈

**Comment by SnowShock35** [comment]
Fixed in [2.3.0](https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-12/files/2615409)
