### ISSUE TITLE
Draconic Wireless Relay don't connect to most blocks.

### ISSUE THREAD

**Issue by mkoz1212** [FTBTeam/FTB-Presents-Direwolf20-1.12#58]
* **Modpack Version**: 2.20

* **Issue**: Draconic Wireless Relays don't connect to most of other mods blocks, like EnderIO or EnvironmenalTech

* **Link to Log or Crash File Paste**: no crash happens

* **Is it Repeatable?**: Yes, easiest way is to have a wireless relay and try to connect to Tier1 VoidOreMiner from EnvironmentalTech. First it is showing the connection, but after a few seconds it disapears.

* **Mod/s Affected**: Draconic Evolution

* **Known Fix**: -

**Comment by SnowShock35** [comment]
Hello @mkoz1212 

Thank you for your contribution to the FTB Presents Direwolf20 1.12 mod-pack. Your involvement greatly helps to improve the quality of the product and keep it bug-free and more enjoyable for everyone. Without your input, the pack would cease to be as good as it is. 

I am delighted to inform you that this issue has been addressed in the recent development of the mod-pack and will be fixed as of version 2.3.0, which will be released publically in the near future. 

As such this issue will now be marked for closure until the update is released and will be closed shortly following its release.

Many thanks once again for your engagement here on the FTBTeam's GitHub.

**SnowShock35 ☃️**

***

> ![SnowShock35](https://cdn.snowshock35.com/avatar-rounded.png)
> ### SnowShock35
> @FTBTeam Pack Developer, Aspiring Full-Stack Engineer, 
> UoN Student, Mod & Modpack Developer, Casual Gamer,
> Nerd, Tea Drinker, Made in the UK 🏳️‍🌈

**Comment by SnowShock35** [comment]
Fixed in [2.3.0](https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-12/files/2615409)
