### ISSUE TITLE
JEI Max Subtypes disabled

### ISSUE THREAD

**Issue by Kanzuke117** [FTBTeam/FTB-Presents-Direwolf20-1.12#6]
* **Modpack Version**: 2.0.0

* **Issue**: Mostly a minor cosmetic issue, but in the update to 2.0.0, `I:maxSubtypes=300` was deleted from `config/jei/jei.cfg`, which has let AE2 add pages upon pages of facade items to the JEI menu, one for almost every block. This can make finding items a pain, especially since AE2 comes high up in JEI's default sort. Searching for `glowing` to find _Extra Utilities 2's_ Glowing Glass gives a full page of Cable Facades combined with _Flat Colored's_ glowing blocks before the item I want.
Also previously hidden is _GenDustry's_ Bee Samples and Genetic Templates, although an argument could be made for wanting to spawn these in using JEI that cannot for Cable Facades.

* **Mod/s Affected**: JEI, AE2, GenDustry

* **Known Fix**: Restoring `maxSubtypes` to 300 would hide both of these sets as it did before, or the Facade could be added to JEI's blacklist, as I assume Thermal Dynamics' Cable Covers are.

**Comment by SnowShock35** [comment]
maxSubtypes was recently removed from JEI. it no longer exists. https://github.com/mezz/JustEnoughItems/commit/d3727c0043de32d83977da1ed1945af9d45cb481
