### ISSUE TITLE
Recipes missing for Simply Jetpacks (Ender IO path) tier 2+ Armor Plating

### ISSUE THREAD

**Issue by woutwoot** [FTBTeam/FTB-Presents-Direwolf20-1.12#61]
* **Modpack Version**: 2.3.0 (latest at this time)

* **Issue**: 
Basically the same issue as reported here:
https://github.com/FTBTeam/FTB-Revelation-2/issues/102

The issue is that there doesn't seem to be a way to craft the tier 2+ Armor Plating for the Ender IO path of SimplyJetpacks. Specifically, while you can craft the Silicon Armor Plating (tier 1) on a crafting table, there is no recipe for: Conductive Iron Armor Plating, Electrical Steel Armor Plating, or Dark Steel Armor Plating. No recipe is shown in JEI, and also the recipe I am familiar with of putting 10 conductive iron in an Alloy Smelter with the Silicon Armor Plating does not work, in fact the Alloy Smelter will not even accept the Silicon Armor Plating. Of course it's possible the recipe is different but it's not shown in JEI.

The Thermal Expansion path has recipes and they are what I would expect, putting 10 ingots of material in the Induction Smelter with the previous armor. These work as expected.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: EnderIO, Simply Jetpacks 2

**Comment by ajruckman** [comment]
Having this problem too... can't even put the items in the alloy smelter.

**Comment by Swivelchair2001** [comment]
Me too. Dosent work, locks me out from getting the Soulariam Jet plate

**Comment by SnowShock35** [comment]
@woutwoot @ajruckman @Swivelchair2001 

Have any of you tried since version 2.4.0 of the mod pack?

**Comment by SnowShock35** [comment]
I have tried crafting the items you described and it definitely is fixed in 2.5.0 of the pack. Please update to the latest version and let me know how you get on. Thanks.
