### ISSUE TITLE
Title screen

### ISSUE THREAD

**Issue by TheGameGeek** [FTBTeam/FTB-Presents-Direwolf20-1.12#62]
* **Modpack Version**: 2.3.0

* **Issue**: Title screen missing images

* **Screenshot of problem**: https://gyazo.com/66d52e86c0535cda7d2af3c2af793eee

* **Is it Repeatable?**: Everytime i load up the pack its like that and its with no texture packs

**Comment by SnowShock35** [comment]
Hi @TheGameGeek,

Apologies for the lateness of my reply. If you are still experiencing this issue, could you try re-installing the pack for me again? It's possible the download did not successfully work. 

Please, let me know how you get on with that.

**SnowShock35 ☃️**

***

> ![SnowShock35](https://cdn.snowshock35.com/avatar-rounded.png)
> ### SnowShock35
> @FTBTeam Pack Developer, Aspiring Full-Stack Engineer, 
> UoN Student, Mod & Modpack Developer, Casual Gamer,
> Nerd, Tea Drinker, Made in the UK 🏳️‍🌈

**Comment by TheGameGeek** [comment]
@SnowShock35 i forgot this was open i believe it was we had added chance cubes into the pack
