### ISSUE TITLE
Refined Storage auto-crafting with fluids no longer works (issue still exists)

### ISSUE THREAD

**Issue by BubbaVB** [FTBTeam/FTB-Presents-Direwolf20-1.12#63]
Modpack Version: 2.3.0

Issue: Prior to the release of 2.2.0 I was able to auto-craft with fluids stored in Refined Storage. I have completely rebuilt the crafting pattern and this did not help resolve the issue. I know there were upgrades to Refined Storage that is in the version so this may be an issue specifically with that mod.

Note:  This issue was reported with the release of 2.2.0 version of the mod pack (https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.12/issues/39).  That ticket was closed stating it was fixed however the issue still exists.  I created a completely new world to test the issue.

Link to Log or Crash File Paste: This issue did not cause a crash so no file is available.

Is it Repeatable?: Yes

Mod/s Affected: Refined Storage version 1.6.4

Known Fix:

**Comment by Kanzuke117** [comment]
I noticed in the changelog:
> 1.6
> - Removed autocrafting with fluids (the bucket filling mechanic). This will be replaced in a later version with native fluid autocrafting, where Crafters can insert fluids to external inventories (raoulvdberge)

> 1.6.1
> - Added fluid autocrafting (raoulvdberge)
> - Added Crafting Upgrade support for fluids on the Exporter, Constructor and Fluid Interface (raoulvdberge)

Are you using the new methods?

**Comment by BubbaVB** [comment]
I believe I was using the fluid autocrafting.  Here is a description of what I was doing:

I have milk & water stored in the refined storage system.  Each in their own 64k Fluid Storage Block.  I'm also using Reborn Storage to house my patterns.  The patterns I'm using that are experiencing issue are:

- Heavy Cream which is made using 1x Mixing Bowl & 1x Milk
- Salt which is made using 1x Pot & 1x Watering Bucket

When I try to craft either one is says the fluid (milk or water) is missing.  Does this answer your question?

**Comment by Kanzuke117** [comment]
So your patterns are regular (non processing) patterns, combining the Pam's item with a bucket of fluid? If so, that's exactly the crafting method that was removed. Have a look here for how it works after 1.6.1: https://refinedstorage.raoulvdberge.com/wiki/autocrafting-with-filled-buckets

**Comment by BubbaVB** [comment]
Kanzuke117 you are correct.  I didn't know that method was removed.  Thanks.

**Comment by SnowShock35** [comment]
Glad to hear you worked this out. Apologies for not getting back to your issue. I've been inactive for some time.
