### ISSUE TITLE
Server crashes when loading new chunks

### ISSUE THREAD

**Issue by sagegwatkin** [FTBTeam/FTB-Presents-Direwolf20-1.12#64]
* **Modpack Version**: FTB Presents Direwolf20 1.12-1.12.2-2.3.0-Server

* **Issue**: Shortly after players generate new chunks the server crashes as the watchdog finds a single server tick taking 60 seconds.
This only occurs as players are generating new chunks and appears to happen directly after console warnings for Thaumcraft causing cascading worldgen lag.

* **Link to Log or Crash File Paste**:
https://paste.feed-the-beast.com/view/d899fd64
https://paste.feed-the-beast.com/view/8ba13add
https://paste.feed-the-beast.com/view/6c5eefaf

* **Screenshots of Crashes**:
https://imgur.com/a/EGCCBsQ

* **Is it Repeatable?**: This happens consistently when players are generating new chunks.

* **Mod/s Affected**: The logs generally show Thaumcraft cascading worldgen lag warnings immediately before crashing.

* **Known Fix**: Starting the server again works but the server crashes the next time players generate new chunks.

**Comment by SnowShock35** [comment]
Hi @sagegwatkin,

Thank you for your patience. Please, could you try to see if your issue persists on version 2.5.0 of the pack?

If it does, could you then try using a new world and see if that still causes an issue. 

If you still have no luck after that I will try to investigate this further for you.

Thanks.

**Comment by egro** [comment]
I'm having the same issue, and I'm running the 2.5 version of the pack.
8 cores, 8 gig or RAM, Ubuntu 16.4.

Exactly the same symptoms as mentioned above.

Crash report:
https://paste.feed-the-beast.com/view/f58c68b0

(Should I open a new incident, or is it OK to keep it in the same thread?)
