### ISSUE TITLE
CANT CRAFT WANDS IN THAUMCRAFT

### ISSUE THREAD

**Issue by KaynC** [FTBTeam/FTB-Presents-Direwolf20-1.12#65]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by belgariondunkelseele** [comment]
well... quite probably :) try going for a gauntlet :)

**Comment by Maat765** [comment]
Find a crystal that has been naturally generated or given to you, sleep, then follow the hint that the book gives you, if you can't figure it out, put 3 different crystals, 1 flint, 1 bowl, 1 redstone together in a normal crafting bench & use the salis mundis on a bookshelf
