### ISSUE TITLE
Dank/Null/Thaumcraft bug

### ISSUE THREAD

**Issue by drose2pye** [FTBTeam/FTB-Presents-Direwolf20-1.12#66]
2.3.0

When a player puts any kind of vis crystal into a dank/null with or without oredictionary enabled, and then picks up any other kind of vis crystals, all the vis crystals go into the dank null as the type of vis crystal in the dank/null. The specific example I discovered this with was that I had put an aqua vis crystal into my dank/null and then flown around the end picking up vis crystals of the other primal essentia, and all of them that I picked up went into my dank/null as vis crystals. This was specifically with a tier 3 dank/null.

No crash file. Did not cause crash

Yes. I later tried to repeat it with an instrumentum vis crystal and it worked just the same. I also attempted the bug with sensus vis crystals and it worked just the same, turning whatever vis crystal I picked up into the sensus vis crystals in my dank/null. I also attempted it with all the different tiers of dank/null(asides from creative) and found that the results were the same, and also when you pull out the vis crystals from the dank/null they remain the kind of crystal that it says in the dank/null.

/dank/null version 1.4.33
Thaumcraft version 6.1.BETA24

I have yet to see any fixes, and tried with several of the different aspect vis crystals, and found that the bug affected all the ones I tried. I did not try it with all of them, but from the data I gathered I think it is safe to assume that the bug can affect any of the various vis crystals allowing a player to exchange vis crystals between different kinds so long as they have one of the desired vis crystal, and other vis crystals to "transform" into the desired kind.
![2018-09-29_13 01 34](https://user-images.githubusercontent.com/43706368/46248498-faf4a980-c3e7-11e8-84e1-1d5d2c557c70.png)
![2018-09-29_13 01 39](https://user-images.githubusercontent.com/43706368/46248499-faf4a980-c3e7-11e8-98b2-ba7e9d32fc1c.png)
![2018-09-29_13 01 43](https://user-images.githubusercontent.com/43706368/46248500-faf4a980-c3e7-11e8-8ae2-4a26208e6fb2.png)
![2018-09-29_13 02 32](https://user-images.githubusercontent.com/43706368/46248501-faf4a980-c3e7-11e8-8bc5-bf2e2e255456.png)
![2018-09-29_13 01 16](https://user-images.githubusercontent.com/43706368/46248502-faf4a980-c3e7-11e8-84fd-a4542eb0da10.png)
![2018-09-29_13 01 17](https://user-images.githubusercontent.com/43706368/46248503-faf4a980-c3e7-11e8-8af1-433be9d3e82d.png)
![2018-09-29_13 01 18](https://user-images.githubusercontent.com/43706368/46248505-faf4a980-c3e7-11e8-9251-e47d6ecb778e.png)
![2018-09-29_13 01 23](https://user-images.githubusercontent.com/43706368/46248506-fb8d4000-c3e7-11e8-88bb-d2aad3f26ccf.png)
![2018-09-29_13 01 27](https://user-images.githubusercontent.com/43706368/46248507-fb8d4000-c3e7-11e8-8984-5ea7dee7f3cc.png)

**Comment by SnowShock35** [comment]
I have confirmed that this is fixed in 2.4.0 of the mod pack.
