### ISSUE TITLE
Refined Storage External Storage doesn't work properly on Extra Utilities Drums

### ISSUE THREAD

**Issue by mkoz1212** [FTBTeam/FTB-Presents-Direwolf20-1.12#67]
* **Modpack Version**: 2.3.0

* **Issue**: Refined Storage External Storage doesn't work properly on Extra Utilities Drums. 
Setup to reproduce: 
Magma Crucible with Import Bus in fluid mode connected to Refined Storage Network with an External Storage (fluid mode) on an Extra Utilities Drum. In addition use a Crafter to Autocraft for example 10 Redstone to 1 Bucket of Destabilized Redstone, which results in an odd number of Buckets in the Drum (in my case it is 1.900mB). Fluid Monitor shows even stranger numbers like 3 Buckets of Destabilized Redstone.

* **Link to Log or Crash File Paste**: no Crash

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Refined Storage & Extra Utilities 

* **Known Fix**: use Refined Storage fluid Cells

**Comment by SnowShock35** [comment]
Hi @mkoz1212,

I have tried to reproduce your issue in the newest version of the pack and I am not having the same result at least from reproducing it given the steps you provided. 

Once released, please test your issue in 2.5.0 and see if you have any luck. If not I can take another look at the issue.

Thank you for your patients.
