### ISSUE TITLE
Can't enter World

### ISSUE THREAD

**Issue by Arkturos** [FTBTeam/FTB-Presents-Direwolf20-1.12#68]
**Modpack Version**: 2.2.0

**Issue**: I am unable to enter my savegame without the game crashing. It displays 
"Loading world - Building terrain" After that, it crashes.

**Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/ce02955f

**Is it Repeatable?** Yes, it happens to me every time.

**Comment by SnowShock35** [comment]
Please update to version 2.5.0 of the mod pack and try again. If you still have no luck. Try reverting to a backup within your backup folder. 

Many thanks
