### ISSUE TITLE
a tool with fortune III, smashing, and smelting does not multiply ingot drops from TiCon nether ores

### ISSUE THREAD

**Issue by Azutte** [FTBTeam/FTB-Presents-Direwolf20-1.12#69]
* **Modpack Version**: 2.3.0 

* **Issue**: For example (this is the only tool I've found so far that can even mine them),[ this resonant fluxbore](https://i.imgur.com/Rz0U9BX.png) drops single ingots from cobalt and ardite; but (at least?) two from, say, a thermal expansion tin ore. 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: well, yeah, I can just mine some more ores and get single ingots from them.

* **Mod/s Affected**: uh, thermal expansion and/or tinker's construct, I guess? I note you can in fact pulverize the ores and get two dusts, so I'm not quite sure where the conflict comes from. 

* **Known Fix**:

**Comment by SnowShock35** [comment]
Thank you for reporting this issue. I will forward it on to the respective authors of Tinkers' Construct and Thermal Expansion / CoFH Core.

**Comment by 016Nojr** [comment]
Mods affected arent maintained anymore, cant fix.
