### ISSUE TITLE
This particular Twilight Forest block (if not more of them) doesn't have a nice localized name when you hover over chiseled bits of it

### ISSUE THREAD

**Issue by Azutte** [FTBTeam/FTB-Presents-Direwolf20-1.12#71]
* **Modpack Version**: 2.3.0

* **Issue**: [https://i.imgur.com/fdMX4n4.png?1](https://i.imgur.com/fdMX4n4.png?1)

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Twilight Forest, Chisel & Bits

* **Known Fix**:

**Comment by Azutte** [comment]
[https://i.imgur.com/hvh6K7M.png](https://i.imgur.com/hvh6K7M.png)

**Comment by SnowShock35** [comment]
Thank you for the issue. I will report this to the respective authors and inform you here once the issue has been deployed to a new version of the mod pack. Thanks for your patients.
