### ISSUE TITLE
Gravestone fails to form *somehow* (???) while fighting ur-ghast in midair

### ISSUE THREAD

**Issue by Azutte** [FTBTeam/FTB-Presents-Direwolf20-1.12#72]
* **Modpack Version**: 2.3.0

* **Issue**: Alright, this is a bit silly, but here's what I was wearing/using/doing.
  * offhand staff of travel
  * back: dark steel chestplate with elytra anvil'd onto it (btw this should use durability or power and doesn't)
  * main hand: some TiCon sword
  * bauble slot: resonant capacitor
  * I was teleporting around in midair while in gliding "stance", which of course negates the need for fireworks. Went up to this Twilight Forest boss, messed around with it for a while, often I'm literally in its hitbox, intentionally. I get fireballed and [a chat message](https://i.imgur.com/3g1IH7Z.png) appears saying "Grave could not be placed". I slime slinged (slung?) the 3400m back, pillar up from the base of the tower, and there's experience sitting there but no items. I guess I could've loaded it for five minutes but I seriously doubt it. Pretty sure my items also didn't "spawn".

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: honestly? no clue. I'm on a server and nowhere near being able to recreate my items. I'm still too upset to bother trying it in single player. 

* **Mod/s Affected**: hm, gravestone mod I guess? I imagine it's something to do with being fireballed, impossible to tell whether I was in the boss's body or what. 

* **Known Fix**:

**Comment by SnowShock35** [comment]
Hi there, 

I am sorry to hear you lost your items I can understand that is really very frustrating. Unfortunately, I am unaware of a gravestone restore command which I know some grave mods have for the particular grave mod installed. It is likely your items fell to the ground when it failed to generate the grave and the time you spent getting back to your grave the items despawned. 

I'm not entirely sure why your grave was not created and again not particularly sure who this issue would be reported too and given there is no way to easily repeat the problem I'm not sure there are any steps to be taken in these circumstances.

**Comment by 016Nojr** [comment]
Mods affected arent maintained anymore, cant fix.
