### ISSUE TITLE
Astral Sorcery sky render issue: Stars dont show up

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [FTBTeam/FTB-Presents-Direwolf20-1.12#75]
* **Modpack Version**: 
v2.3.0, running on a dedicated server

* **Issue**:
Astral Sorcery's special render for the overworld seems to break when time manipulation (like sleeping or the blood magic imperfect ritual stone with a lapis block). Specifically, by break I mean that the stars in the night sky stop rendering. Images available at https://github.com/HellFirePvP/AstralSorcery/issues/875

Note that this is a purely cosmetic issue, the telescope etc do all continue to work and show stars as expected.

* **Link to Log or Crash File Paste**:
No relevant errors in log on either server or clientside, no AS logs whatsoever past "Normal" loading, if requested I can provide a full startup and play log

* **Is it Repeatable?**:
Somewhat, though a definite cause seems to be sleeping or forcing night as described above

* **Mod/s Affected**: 
Astral Sorcery

* **Known Fix**:
it would seem that setting the time to night (via `/time set night`) fixes the issue, though this has the effect of moving the world's time backwards, which resets things such as local chunk difficulty.

**Comment by SnowShock35** [comment]
Thank you for reporting this issue. From the issue, you linked it seems the issue is still open and awaiting a fix from the author. I will leave this issue open until it is fixed.

**Comment by 016Nojr** [comment]
Linked Mod issue has been closed.
