### ISSUE TITLE
Refined storage Crafter cannot be chained on EnderIO machines

### ISSUE THREAD

**Issue by mkoz1212** [FTBTeam/FTB-Presents-Direwolf20-1.12#76]
* **Modpack Version**: 2.3.0

* **Issue**: Refined Storage Crafter cannot be chained on the same machine as for example with Thermal Expansion ones.

* **Link to Log or Crash File Paste**: No Crash

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Refined Storage, EnderIO

* **Known Fix**: Not Available

**Comment by mkoz1212** [comment]
It actually works, but it's not named properly and therefore also hard to identify in the pattern monitor from Refined Storage.

**Comment by SnowShock35** [comment]
This might have been addressed in a later version of Refined Storage, it will have updated within the new update coming out in a day or so. If not then it might be worth bringing up on the mod's issue tracker as a suggestion. 

Refined Storage issue tracker:
[raoulvdberge/refinedstorage](https://github.com/raoulvdberge/refinedstorage/issues)
