### ISSUE TITLE
Update Building Gadgets

### ISSUE THREAD

**Issue by Flamebom** [FTBTeam/FTB-Presents-Direwolf20-1.12#80]
* **Modpack Version**: 2.3.0 

* **Issue**: Without the updated version of Building Gadgets, using them instantly crashes the game which makes Building Gadgets useless right now.

* **Link to Log or Crash File Paste**: 
Direct Link
https://pastebin.com/dJqDv2fi
Issue reported to mod author
https://github.com/Direwolf20-MC/BuildingGadgets/issues/127

* **Is it Repeatable?**:Yes 

* **Known Fix**: Just don't use building gadgets :) .

**Comment by SnowShock35** [comment]
Can you please try to recreate your issue on 2.4.0.

Thanks.

**Comment by Flamebom** [comment]
I'm pretty sure it's fixed without even testing because direwolf said

![image](https://user-images.githubusercontent.com/43626865/54570191-e22e7f00-499a-11e9-9d9d-ed0c29789853.png)


the version in the current pack is 2.4.5 and old was like 1.6.7 or something
