### ISSUE TITLE
Deep Dark Crash

### ISSUE THREAD

**Issue by kerblaster** [FTBTeam/FTB-Presents-Direwolf20-1.12#81]
* **Modpack Version**: 2.3.0

* **Issue**: The game crash when I enter to the dark dark.

* **Link to Log or Crash File Paste**: 
[crash-2018-11-11_17.08.55-client.txt](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.12/files/2569558/crash-2018-11-11_17.08.55-client.txt)

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Extra utilities

* **Known Fix**: do not go into deep dark

**Comment by SnowShock35** [comment]
Please, remove DiscordRP and any other mods you have added before reporting issues with the pack. We do not support the addition of mods to the pack.
