### ISSUE TITLE
Client crash - 

### ISSUE THREAD

**Issue by Momibelle** [FTBTeam/FTB-Presents-Direwolf20-1.12#83]
* **Modpack Version**:  FTBPresentsDirewolf20112-2.4.0-1.12.2

* **Issue**: Client crash - undetermined

* **Link to Log or Crash File Paste**: https://pastebin.com/7jSkXe0A

* **Is it Repeatable?**: sure is!

* **Mod/s Affected**: no ideas which ones, please look at the crash log above, thanks!

Hope you can help!
Momibelle

**Comment by SnowShock35** [comment]
Your game ran out of memory. You'll need to increase the memory allocated to the game. It is probably a good idea to allocate 6GBs for the game to run without these issues.
