### ISSUE TITLE
Server Crash trying to reboot a refined storage network with a lever (ender io involved)

### ISSUE THREAD

**Issue by Eldhelion** [FTBTeam/FTB-Presents-Direwolf20-1.12#86]
* **Modpack Version**: 2.3.0

* **Issue**:  in a nutshell : server crash and unable to reload the server map with error.
long story:
I had a 5x5x5  reborn storage multiblock machine, thinking in upgrading but not having space to do it on the overwold.
I built a 11x11x11 reborn storage multiblock machine, inside a 13x13x13 compact machine.
In one side of the multiblock I placed a io port hoping to use a Item conduit from ender IO to input my patterns from  8 double chests. 
not a single pattern was imported.
I put the ender io cable for refined storage, and linked the compact machine to my network, cheked in the pattern manager, the multiblock was not recognised.

Like, every single person that someday had to fiddle with eletronics, I placed a lever on the network core, and then proceded to power off, instantly the server crashed

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/bb051ece

* **Is it Repeatable?**: dont know

* **Mod/s Affected**: ender IO, refined storage, and maybe reborn storage

* **Known Fix**:  not aware

**Comment by SnowShock35** [comment]
Hi there, 

Have you been able to reproduce your issue in version 2.4.0 of the pack? If so can you be more clear as to what it is the network core is? I am not aware of a block called a network core. 

Thanks for your patients.
