### ISSUE TITLE
RS Storage disks are within the disk drive, but do not show any items or storage capacity. Items are locked inside.

### ISSUE THREAD

**Issue by Murdurtroll** [FTBTeam/FTB-Presents-Direwolf20-1.12#87]
* **Modpack Version**: Refined Storage 1.6.4 (Direwolf20-1.12.2)

* **Issue**: I have a refined storage system setup, with 6 64K disk drives, furthermore I have an external storage bus connected to a drawer controller, which is connected to several drawers for items I have in bulk. The following issue occured; I decided to go AFK for some time to let all mining run etc. Therefore I put all my armor/rings/inventory into the RS system. At my returnal I wanted to get my items out, but it appeared that everything which was stored on the disks is not visible in the RS system. All items which were are in the external storage drawers are visible.

Thus, I tried to check what the problem was, broke the RS controller and replaced it, no difference.
I took the disks out of the disk drive, broke the disk drive, put the disks back in but no items visible in the system. I did notice that new items which came in via my ender chest onto which an importer was connected were not placed in the RS system. In matter of fact, I cannot place any item in the RS system (I can place items in which are connected through the drawer system).

At last, I checked my disk drive, it says 0/0 space used/available, whilst 6 64K disks were inside. I manually made a 1K disk, put it in and it showed 0/1000. Thus, the issue seems to be that the 64K disks which were inside are suddenly not recognized anymore, and all my items are locked.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: The issue is still occuring.

* **Mod/s Affected**: I think it is only Refined Storage 1.6.4, maybe the Refined Storage Addons as well, but do not know for sure.

* **Known Fix**: I have read several threads and forums, but did not find any simmular issue. Anyone can help about this?

I tried my best provide all information, if any is lacking please let me know.

**Comment by Murdurtroll** [comment]
Update:
Still not working, but I found some interesting things. Importers are not working, exporters are working if I E.G. make a crafter recipe it does output the item into the furnace, but than it does not import the finished product, as the 64K storage disks seem broken.

**Comment by Murdurtroll** [comment]
does anyone know if this forum is still live?

**Comment by Murdurtroll** [comment]
you know. At a certain point it just feels sad to see what is all just... destroyed... by some bug.... thinking you can safely store all your goodies... but... boom...

**Comment by Murdurtroll** [comment]
Somewhere... on the other side of the interwebs... hopefully someone is looking into this...
Greetings.

**Comment by Murdurtroll** [comment]
I might start blogging here. But I do not think this will lead me into much fame... Since probably my blog would get the same amount of comments as this thread. But hey, commetns are not important, it is about that 1 person who might read it and secretly enjoy my agony.

**Comment by Gunsrude** [comment]
I only ask this because I've done this before, but, are you sure you're not trying to stick a 64k **Fluid** Storage disk in there?

**Comment by Murdurtroll** [comment]
Dear Gunsrude,

thank you so much for your reply, this means so much for me. Unfortunately that seems not to be the issue. Everything operated well, with the correct disks, and suddenly those are not accepted/recognized anymore.

Would you please rate my blog 0/5 stars?

thanks! =D

**Comment by SnowShock35** [comment]
Hi @Murdurtroll,

Thank you for patiently waiting. I apologise for not replying sooner, there has been a lot going on in my personal life over the last few months so I have not been able to monitor this issue tracker.

I am not entirely sure what might be causing you this issue. Have you tried updating to the latest version of Refined Storage? That could potentially fix the issue you are having. If not, I do have an update coming out in the next day or so which updates a large majority of mods so hopefully, this will solve your issue. 

If the issue still persists, my advice would be to roll back to the last backup, which you will find in the backups folder in your instance folder. 

Thanks again for your patients.

**Comment by Murdurtroll** [comment]
Hi SnowShock,

You cannot imagine how delighted I am that you have been able to provide feedback to my issue.
It has been a cold winter, and Minecraft was already been given up... Well almost.. Last week I was doubting whether to delete the link to this thread, but fortunately I received a mail that a reply was given.

I will check in-game if anything is changed with any updates.

I will let you know what the outcome will be.
