### ISSUE TITLE
FPS issue 

### ISSUE THREAD

**Issue by 19celtic71** [FTBTeam/FTB-Presents-Direwolf20-1.12#88]
* **Modpack Version**: 1.12 v2.3.0

* **Link to Log or Crash File Paste**:  n/a

* **Is it Repeatable?**: yes

* **Mod/s Affected**: n/a

* **Known Fix**: n/a

Once logged into the game my FPS drop to 1 or less, but when on the main screen to choose multiplayer and options I'm at normal FPS with no lag

Operating System
			Windows 10 Pro 64-bit
		CPU
			AMD FX-8370	45 °C
			Vishera 32nm Technology
		RAM
			16.0GB Dual-Channel DDR3 @ 666MHz (9-9-9-24)
		Motherboard
			MSI 990FXA-GD80 (MS-7640) (CPU 1)	59 °C
		Graphics
			DELL ST2420L (1920x1080@60Hz)
			HP L2208w (1680x1050@60Hz)
			2048MB ATI AMD Radeon R9 200 Series (XFX Pine Group)	54 °C
		Storage
			931GB Western Digital WDC WD10EZEX-60WN4A0 ATA Device (SATA )	36 °C
			931GB Hitachi HDS721010CLA332 ATA Device (SATA )	33 °C
		Optical Drives
			No optical disk drives detected
		Audio
			Realtek High Definition Audio

**Comment by SnowShock35** [comment]
Hi @19celtic71,

How many gigabytes of RAM do you have allocated to the game? Also,  what other applications do you have running in the background? Try reducing the render distance or making sure V-Sync is disabled in the Minecraft options.
