### ISSUE TITLE
Thaumcraft Stabilizer crash

### ISSUE THREAD

**Issue by tmbates12** [FTBTeam/FTB-Presents-Direwolf20-1.12#9]
* **Modpack Version**: 2.0.0

* **Issue**: Upon applying any source of power to the Stabilizer, the server will crash instantly, and this seems to be a known bug with the version of Thaumcraft 6 we are using.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/c4661bbc

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Thaumcraft 6 Beta 15

* **Known Fix**: This issue was fixed in Thaumcraft 6 Beta 17 so an update to the modpack would fix this: 
https://github.com/Azanor/thaumcraft-beta/issues/969

**Comment by SnowShock35** [comment]
Thanks for the report. I have updated Thaumcraft to Beta 17 in version 2.1.0 which will be released shortly. 

Thanks for helping to better the packs stability. 👍
