### ISSUE TITLE
Can't Pour from Faucets in Tinkers' Construct

### ISSUE THREAD

**Issue by BunsenGyro** [FTBTeam/FTB-Presents-Direwolf20-1.12#90]
* **Modpack Version**: 2.3.0

* **Issue**: Tinkers' Construct Faucet won't work, on my friend's server. Upon right clicking a faucet with Molten Glass in the forge, the liquid will be poured for only a brief moment into a basin or casting table, before stopping itself, regardless of the duration of the right click. Any Molten Glass liquid that has been poured from these very brief moments eventually disappear and reappear in the forge, as if you had never poured any liquid.

* **Link to Log or Crash File Paste**: Unable to provide, as it does not crash the game.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Tinkers' Construct

**Comment by SnowShock35** [comment]
This issue appears to be fixed in the new version that will be released as a beta within the next day or two. 

Please try replicating your issue and if you're still having it let me know. 

Thanks.
