### ISSUE TITLE
Latest update has memory leak

### ISSUE THREAD

**Issue by Phase-Shifter** [FTBTeam/FTB-Presents-Direwolf20-1.12#93]
Just downloaded the latest update, and framerate is too low to play while memory usage in constantly increasing.

I thought the update might have an issue with items placed in the world, so I tried creating a new world, but that didn't fix the issue.

**Comment by SnowShock35** [comment]
This appears to be fixed in the development version. It will be released as a beta within the next day or so. Please try it and let me know how you get on, thanks.
