### ISSUE TITLE
Ability to duplicate ender pearls in TiCon smeltery

### ISSUE THREAD

**Issue by AquatikJustice** [FTBTeam/FTB-Presents-Direwolf20-1.12#94]
* **Modpack Version**: 2.4.0

* **Issue**: There is a misconfiguration that allows a player to put 1 ender pearl in the smeltery, giving them 576 mB of Resonant Ender, but they can then cast that into a gem cast at 250 mB per pearl to get 2 ender pearls (plus some leftover Resonant Ender fluid). This can be quickly and easily automated to make an infinite ender pearl generator.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Tinkers' Construct

* **Known Fix**: Remove the ender pearl smeltery recipe and re-add it w/ CraftTweaker, giving only 250 mB of resonant ender fluid per pearl. Code to is below:

mods.tconstruct.Melting.removeRecipe(<liquid:ender>, <minecraft:ender_pearl>);
mods.tconstruct.Melting.addRecipe(<liquid:ender> * 250, <minecraft:ender_pearl>);

**Comment by SnowShock35** [comment]
It appears on updating mods from the last update that the issue has been fixed by the respective author, which mod I am not sure of. Nevertheless, it will be fixed in 2.5.0 which will be out in a day or so. 

Thanks for your patients and reporting the issue.
