### ISSUE TITLE
Thaumcraft Bug

### ISSUE THREAD

**Issue by Maat765** [FTBTeam/FTB-Presents-Direwolf20-1.12#96]
* **Modpack Version**: 2.4.0

* **Issue**:When breaking any container with the focus called "Break" in Thaumcraft, the contents do not drop.

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: Thaumcraft Beta-26

I have one more question,
In the next update, could there possibly be furniture added? Like, Crayfish, or decocraft?

Thanks,
Maat

**Comment by SnowShock35** [comment]
Hi @Maat765,

I have tried to re-create your issue in the new version of the pack, that will be released within the next day or so, and found that breaking any containers with a break foci does cause the contents and the block to drop. Could you give it another try once 2.5.0 comes out and let me know as soon as you can if you're still having issues or not?

As for your other query, this would be down to Direwolf20, he decides on the mod packs content. Personally, I feel these mods would not be a good idea to add to the pack as they add a lot of blocks and therefore textures, this means that Minecraft has to store more textures in memory making the overall memory allocation for the game higher which as a result means less people would be able to play the pack and the entry pc requirements would significantly increase also. 

Feel free to add it yourself if you do wish to use the mod, just be sure to remove it before reporting issues as we don't support adding and removing mods from the pack.

Thanks for reporting the issue and your patience.

**Comment by Maat765** [comment]
It was whenever I broke an iron chest with it, I will try testing it again
on the next update. Another suggestion, as direwolf20 has a bunch of magic
mods, maybe you guys could add roots 2?

Thanks,
Maat

**Comment by SnowShock35** [comment]
Just tried on an Iron Chest with no issues. Again, it would be a question for Direwolf20, not myself or the FTB Team.

Hope this helps :-)

**Comment by Maat765** [comment]
Weird,  Ill try it next time I load up dw20 and record it I guess
