### ISSUE TITLE
Binnie's Botany Trowel

### ISSUE THREAD

**Issue by HojoCat** [FTBTeam/FTB-Presents-Direwolf20-1.12#97]
* **Modpack Version**: 2.4.0

* **Issue**: Binnie's Botany Trowel does not work when used on grass or dirt or anything I can find.
Without the trowel working the entire Binnie's Botany mod does not work. Flowers cannot be created and the tileworker machine is just an expensive door stop.

* **Is it Repeatable?**: always

* **Mod/s Affected**: Binnie's Botany is affected. I do not know which mod is the cause.

**Comment by grazazel** [comment]
I also have this same problem. can confirm it is all the trowels. They make the sound but not changing the ground

**Comment by SnowShock35** [comment]
This has been fixed in the upcoming version of the pack. It should be released within the next day or so.

Thank you for reporting this issue and your patience.
